import type { BackendProcess, CLIBackend } from '@autonomy/agent-manager';
import type { LLMCallback } from '@pyx-memory/core';

export interface MemoryLLMHandle {
  callback: LLMCallback;
  shutdown: () => Promise<void>;
}

/**
 * Bridge agent-forge's CLIBackend to pyx-memory's LLMCallback interface.
 *
 * Spawns a dedicated backend process for memory lifecycle operations
 * (consolidation, summarization, fact extraction, entity resolution).
 *
 * SECURITY NOTE: `skipPermissions: true` is required because this process
 * runs headless (no user to approve prompts). The prompts sent to this
 * callback are server-generated by pyx-memory's lifecycle engine, never
 * directly from user input. The system prompt constrains the process to
 * memory management operations only.
 */
export async function createMemoryLLMCallback(backend: CLIBackend): Promise<MemoryLLMHandle> {
  const process: BackendProcess = await backend.spawn({
    agentId: 'memory-lifecycle',
    systemPrompt:
      'You are a memory management assistant. Follow instructions precisely. Output only what is requested.',
    skipPermissions: true,
    sessionPersistence: false,
  });

  const callback: LLMCallback = async (prompt: string): Promise<string> => {
    return process.send(prompt);
  };

  return {
    callback,
    shutdown: () => process.stop(),
  };
}
